### ISSUE TITLE
-

### ISSUE THREAD

**Issue by ghost** [renatolinsjr/React-Calculadora#1]
Vou adicionar um recurso! Posso?

**Comment by pedroguilhermelima** [comment]
Vou colocar a opção de mover... é porque parado é chato ;D Como mover? Para a pessoa movimentar na tela!

**Comment by renatolinsjr** [comment]
Pode sim, fique a vontade!

**Comment by pedroguilhermelima** [comment]
Manooooo olha que legal ;D https://jqueryui.com/draggable/

Javascript
~~~~
$( function() {
    $( "#draggable" ).draggable();
  } );
~~~~

HTML
~~~~
<div id="draggable" class="ui-widget-content">
  <p>Drag me around</p>
</div>
~~~~

**Comment by pedroguilhermelima** [comment]
> Manooooo olha que legal ;D https://jqueryui.com/draggable/
> 
> Javascript
> 
> ```
> $( function() {
>     $( "#draggable" ).draggable();
>   } );
> ```
> HTML
> 
> ```
> <div id="draggable" class="ui-widget-content">
>   <p>Drag me around</p>
> </div>
> ```

Você adiciona isso e a sua calculadora movimenta na tela. ;D

**Comment by pedroguilhermelima** [comment]
Vamos sair da Web e fazer Desktop ;D 
Tem como? Electron! ^^

**Comment by pedroguilhermelima** [comment]
A minha calculadora... Rs "Se chama calreact"

**Comment by pedroguilhermelima** [comment]
Outro recurso maneiro sombra com efeito hover ;D https://codepen.io/sdthornton/pen/wBZdXq/

**Comment by pedroguilhermelima** [comment]
Exemplo

~~~~
.card-1 {
  box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
  transition: all 0.3s cubic-bezier(.25,.8,.25,1);
}

.card-1:hover {
  box-shadow: 0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22);
}

.card-2 {
  box-shadow: 0 3px 6px rgba(0,0,0,0.16), 0 3px 6px rgba(0,0,0,0.23);
}
~~~~

**Comment by pedroguilhermelima** [comment]
**Tirei o background acho melhor sem ^^** Coloquei apenas esse background no display

**Comment by pglapds** [comment]
> Pode sim, fique a vontade!

Para você ver a diferença veja em https://repl.it/@pglapds/Calcula
